---
title: "Prepare CITE-seq data"
output: html_notebook
---

```{r}
library(Matrix)
```

# Sanger Institute Covid data

## h5ad to Seurat 

Downloaded h5ad file from this [link](https://covid19.cog.sanger.ac.uk/submissions/release2/vento_pbmc_processed.h5ad).

```{R}
rootDir <- "/data/projects/punim0613/JiaDong/PhiSpace/data/Covid/"
reticulate::use_condaenv("st")
sc <- reticulate::import("scanpy")
anndata <- sc$read_h5ad(
  paste0(rootDir, "SangerAutoimmune/vento_pbmc_processed.h5ad")
)
ventoRNAumap <- anndata$obsm[["X_umap"]]
dimnames(ventoRNAumap) <- list(
  anndata$obs_names$values,
  c("umap1", "umap2")
)
saveRDS(
  ventoRNAumap,
  paste0(rootDir, "Vento-Tormo/ventoRNAumap.rds")
)
```




## Seurat to SCE 

```{r}
dat_dir <- "/data/projects/punim0613/JiaDong/PhiSpace/"

query <- readRDS(
  paste0(
    dat_dir,
    "data/Covid/Vento-Tormo/vento_pbmc_processed.rds"
  )
)
featNames <- rownames(query)
idx <- grepl("AB_", featNames)
```

Separate ADT and RNA features.

```{r}
pathADT <- paste0(
    dat_dir,
    "data/Covid/Vento-Tormo/ADT_uncorrected_names.rds"
)
pathRNA <- paste0(
    dat_dir,
    "data/Covid/Vento-Tormo/RNA.rds"
)

if(!(file.exists(pathADT) & file.exists(pathRNA))){
  
  queryADT <- query[idx,]
  query <- query[!idx,]
  assay(query, "counts") <- as(assay(query, "counts"), 'CsparseMatrix')
  query <- scranTransf(query)
  saveRDS(queryADT, pathADT)
  saveRDS(query,pathRNA)
} 
```


# Haniffa lab Covid data


```{r}
dat_dir <- "/data/projects/punim0613/JiaDong/PhiSpace/"
pathADT <- paste0(
    dat_dir,
    "data/Covid/Haniffa/HaniffaADT.rds"
)
pathRNA <- paste0(
    dat_dir,
    "data/Covid/Haniffa/HaniffaRNA.rds"
)


if(!(file.exists(pathADT) & file.exists(pathRNA))){
  
  reticulate::use_condaenv("st")
  sc <- reticulate::import("scanpy", convert = T)
  pd <- reticulate::import("pandas", convert = T)
  dat <- sc$read_h5ad(
    paste0(
      dat_dir,
      "data/Covid/Haniffa/covid_portal_210320_with_raw.h5ad"
    )
  )
  
  
  ## subsample
  keepProp <- 0.1
  ann <- as.data.frame(dat$obs)
  id <- as.character(ann$sample_id)
  idTab <- table(id)
  idNames <- names(idTab)
  set.seed(523234)
  selectIdx <- lapply(
    idNames,
    function(idName){
      
      fullIdx <- which(id == idName)
      toSelect <- round(idTab[idName] * keepProp)
      selectIdx <- sample(fullIdx, toSelect)
      return(selectIdx)
    }
  )
  selectIdx <- unlist(selectIdx)
  
  varDat <- dat$var
  adtIdx <- varDat$feature_types == "Antibody Capture"
  obsNames <- dat$obs_names$values[selectIdx]
  
  # ADT
  varNames <- dat$var_names$values[adtIdx]
  varNames <- gsub("AB_", "", varNames)
  counts <- dat$layers["raw"][selectIdx,adtIdx]
  dimnames(counts) <- list(
    obsNames,
    varNames
  )
  counts <- as(counts, 'CsparseMatrix')
  sce <- SingleCellExperiment::SingleCellExperiment(
    list(counts = t(counts)),
    colData = ann[selectIdx,]
  )
  sce <- PhiSpace::CLRnorm(sce)
  saveRDS(sce, pathADT)
  
  # RNA
  varNames <- dat$var_names$values[!adtIdx]
  counts <- dat$layers["raw"][selectIdx,!adtIdx]
  dimnames(counts) <- list(
    obsNames,
    varNames
  )
  counts <- as(counts, 'CsparseMatrix')
  sce <- SingleCellExperiment::SingleCellExperiment(
    list(counts = t(counts)),
    colData = ann[selectIdx,]
  )
  rm(counts); gc()
  # scran transform
  sce <- PhiSpace::scranTransf(sce)
  saveRDS(sce, pathRNA)
} 
```


## Rename ADT according to Vento immune data
```{r}
dat_dir <- "/data/projects/punim0613/JiaDong/PhiSpace/"

# Query
query <- readRDS(
  paste0(
    dat_dir,
    "data/Covid/Haffina/HaffinaADT.rds"
  )
)

quVar <- rownames(query) 

## Generated by ChatGPT + manual work
cd_aliases <- list(
  C5AR1 = "CD88", CCR3 = "CD193", CCR4 = "CD194", CCR5 = "CD195", CCR6 = "CD196",
  CCR7 = "CD197", CD40LG = "CD154", CEACAM1 = "CD66a", CEACAM8 = "CD66b", CR1 = "CD35",
  CTLA4 = "CD152", CXCR3 = "CD183", CXCR4 = "CD184", CXCR5 = "CD185", DPP4 = "CD26",
  ENTPD1 = "CD39", FAS = "CD95", FASLG = "CD178", FCER2 = "CD23", FCGR2A = "CD32a",
  HAVCR2 = "CD366", ICAM1 = "CD54", ICOS = "CD278", ITGA2 = "CD49b", ITGA2B = "CD41",
  ITGA4 = "CD49d", ITGA6 = "CD49f", ITGAE = "CD103", ITGAL = "CD11a/CD18", ITGAM = "CD11b",
  ITGAX = "CD11c", ITGB1 = "CD29", ITGB2 = "CD18", LAG3 = "CD223", LAIR1 = "CD305",
  LAMP1 = "CD107a", LILRB1 = "CD85j", MCAM = "CD146", MME = "CD10", MSR1 = "CD204",
  NT5E = "CD73", PD1 = "CD279", PDCD1LG2 = "CD273", PECAM1 = "CD31", PROM1 = "CD133",
  PVR = "CD155", SDC1 = "CD138", SELP = "CD62P", SIGLEC1 = "CD169", SLAMF1 = "CD150",
  SLAMF7 = "CD319", THY1 = "CD90", TNFRSF17 = "CD269", TNFRSF8 = "CD30", TNFRSF9 = "CD137",
  TNFSF9 = "CD137L", VCAM1 = "CD106",
  ## Following are manual work
  Rat_IgG2b_K_Iso = "Rat-IgG2b",
  `CEACAM1/5/6` = "CD66a/c/e",
  `TCR_Va24-Ja18` = "TCR-V-24-J-18",
  `TCR_Va7.2` = "TCR-V-7.2",
  `TCR_Vg2` = "TCR-V-2",
  `TCR_Vg9` = "TCR-V-9",
  CDH1 = "Cadherin",
  CD1C = "CD1c"
)

quVar_cd <- sapply(
  quVar, 
  function(adt) {
    if (adt %in% names(cd_aliases)) {
      return(cd_aliases[[adt]])
    } else {
      return(adt)
    }
  }
)

rownames(query) <- quVar_cd


saveRDS(
  query,
  paste0(
    dat_dir,
    "data/Covid/Haniffa/HaniffaADT.rds"
  )
)
```


























